### ISSUE TITLE
Synthetic Data for Semantic Segmentation

### ISSUE THREAD

**Issue by mr-rhombus** [aireveries/RarePlanes#5]
I'd like to use the synthetic data for semantic segmentation, but don't want to download the entire 211GB. What command should I run to download only the relevant data?

**Comment by thomashossler** [comment]
The full synthetic dataset is indeed 211GB, including 146GB of RGB images and 65GB of masks, which you will both need for training semantic segmentation models. Otherwise, you could create the semantic segmentation masks using the polygons available in the json files but you would still have to download the RGB images.
